# Generated by Django 5.2.6 on 2025-11-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aboutpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutpage_title', models.CharField(max_length=500)),
                ('aboutpage_img', models.CharField(max_length=500)),
                ('aboutpage_desc', models.TextField()),
                ('aboutpage_uploading', models.FileField(default=None, max_length=500, null=True, upload_to='aboutpage')),
            ],
        ),
        migrations.CreateModel(
            name='PromptLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
