# Generated by Django 5.2.6 on 2025-11-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_title', models.CharField(max_length=500)),
                ('slider_img', models.CharField(max_length=500)),
                ('slider_desc', models.TextField()),
                ('slider_uploading', models.FileField(default=None, null=True, upload_to='media')),
            ],
        ),
    ]
