# Generated by Django 5.2.6 on 2025-09-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='datetime_post',
            field=models.DateTimeField(default=None),
        ),
    ]
