# Generated by Django 5.2.6 on 2025-11-14 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpanel', '0002_alter_post_datetime_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('datetime_post', models.DateTimeField(default=None)),
                ('category_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogpanel.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
